def raise_error(e):
	print("")
	print("###########################################")
	print("## ❌ ERROR CAUGHT; STOPPING             ##")
	print("###########################################")
	print(f"{e}".replace('\\n', '\n'))
	print("###########################################")
	print("## ❌ ERROR CAUGHT; END OF MESSAGE       ##")
	print("###########################################")
	exit()